# Generated by Django 2.1.2 on 2018-10-26 06:46

import Insurances.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insu_id', models.AutoField(primary_key=True, serialize=True)),
                ('cust_id', models.IntegerField(default=101)),
                ('insu_acc_no', models.IntegerField(default=Insurances.models.get_random_id)),
                ('insurance_type', models.CharField(choices=[('h', 'home'), ('v', 'vehical'), ('p', 'personal')], max_length=100)),
                ('total_insurance', models.CharField(choices=[('a', 'one Lakh'), ('b', '5 Lakh'), ('c', '10lakh')], max_length=200)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transacts',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField(default=101)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactss', to='Insurances.Insurance')),
            ],
        ),
    ]
