# Generated by Django 2.1.2 on 2018-10-29 05:19

import Insurances.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insurances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacts',
            name='Insurance_accnt',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insu_acc_no',
            field=models.IntegerField(default=Insurances.models.get_random_id, unique=True),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Insurances.Insurance'),
        ),
    ]
