# Generated by Django 2.1.2 on 2018-10-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurances', '0002_auto_20181029_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacts',
            name='Insurance_accnt',
            field=models.IntegerField(choices=[('a', 'one Lakh'), ('b', '5 Lakh'), ('c', '10lakh')]),
        ),
    ]
