# Generated by Django 2.1.2 on 2018-10-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insurances', '0003_auto_20181029_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacts',
            name='Insurance_accnt',
            field=models.CharField(choices=[('a', 'one Lakh'), ('b', '5 Lakh'), ('c', '10lakh')], max_length=100),
        ),
    ]
